name: Build Push Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: demo-app
  CLUSTER_NAME: devops-eks

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login To ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Image
      run: |
        docker build -t demo-app:${{ github.sha }} .

    - name: Tag Image
      run: |
        docker tag demo-app:${{ github.sha }} \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/demo-app:${{ github.sha }}

    - name: Push Image
      run: |
        docker push \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/demo-app:${{ github.sha }}

    # - name: Install Trivy
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install wget -y
    #     wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.64.1_Linux-64bit.deb
    #     sudo dpkg -i trivy_0.64.1_Linux-64bit.deb

    # - name: Scan Image
    #   run: |
    #     trivy image \
    #     --severity HIGH,CRITICAL \
    #     ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/demo-app:${{ github.sha }}

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Verify AWS Identity
      run: |
        aws sts get-caller-identity  

    - name: Configure kubeconfig
      run: |
        aws eks update-kubeconfig \
        --region ap-south-1 \
        --name devops-eks

    - name: Helm Upgrade
      run: |
        helm upgrade --install demo-app ./demo-app \
        --set image.repository=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/demo-app \
        --set image.tag=${{ github.sha }}

    - name: Verify Rollout
      run: |
        kubectl rollout status deployment/demo-app